export const CHANGE_ENTRY = 'CHANGE_ENTRY';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';
export const ADD_ENTRY = 'ADD_ENTRY';
export const ADD_EMPTY_ENTRY = 'ADD_EMPTY_ENTRY';
export const CHANGE_ENTRY_TYPE = 'CHANGE_ENTRY_TYPE';
